### ISSUE TITLE
Feature-Request: Red Color Highlighting For God's Messages

### ISSUE THREAD

**Issue by ghost** [bontibon/kjv#10]
Hello,

Much like a real Bible, it would be cool if there would be the ability to see God or Jesus speaking in red text, which is what I've seen in most Bibles out there to let you know when God or the son of God, Christ, is speaking.

I'm not sure if this would be entirely based on the type of terminal you're running the application in as well, so please let me know if this would be a possibility as I believe you would most likely have to painstakingly know the exact verses in which God or Jesus is speaking throughout the Bible to truly know which to colorize in red text.

Anyway, please let me know if this would need a pull request instead.

Love this program a ton, thanks for creating this!

**Comment by bontibon** [comment]
Thanks for the suggestion, but I don't plan on adding this.
