### ISSUE TITLE
New Command Line Options

### ISSUE THREAD

**Issue by Traap** [bontibon/kjv#15]
I have been using kjv about a 1 year now.  I wanted to modify the command line options as follows below.

usage: kjv [flags] [reference...]

Flags:
  -A num  number of verses of context after matching verses
  -B num  number of verses of context before matching verses
  -C      show matching verses in context of the chapter
  -b      Blank line between verses.
  -d      Disable italic highlighting.
  -h      show help
  -l      list books
  -v      show version number
  -w      maximum line width (default is 80)

I forked your repository today to start make the changes.  I will create a pull-request for your review.

The rational for this changes are quite simple.  I am a Vimmer.   I take notes while listening or watching videos'.

I use the following command to insert text directly into my notes:

**:r!kjv eph 2:8-9**

-b provides a blank line between versus
-d disables italics so I get plain text
-v shows the program version number
-w 40 wraps text to 40 columns

I would like to run:

**:r!kjv eph 2:8-9 -b -d -w 40**

**Comment by Traap** [comment]
Status update:  Thus far I have made 7 commits to my forked kjv-1 branch.  The proposed command line options are working.   I detailed my progress with each commit.

Cool vim integration.  I use the gk (get KJV) mapping below to read KJV text directly into vim/neovim.
This speeds up note taking.  Also, because the mapping yanks the line, I can add kjv command line arguments.  Bonus!

```vim
map gk 0mMvg_"ky :exec "r!kjv  -b -d -w 65" getreg("k")<cr>
```

John 3:16
dan 7:4-5 -A 3 -B 3
rev 22:1

Any feedback before a  pull-request is welcomed.

**Comment by Traap** [comment]
Status update: Example outputs are shown below.  Note the highlighted version was converted to markdown manually.

```bash
kjv -v
1.1.1.97
```

```bash
kjv 1 cor 15:1-4 -b -w 40
```

```
1 Corinthians

15:1   Moreover, brethren, I declare 
       unto you the gospel which I 
       preached unto you, which also 
       ye have received, and wherein 
       ye stand; 

15:2   By which also ye are saved, 
       if ye keep in memory what I 
       preached unto you, unless ye 
       have believed in vain. 

15:3   For I delivered unto you 
       first of all that which I 
       also received, how that 
       Christ died for our sins 
       according to the scriptures; 

15:4   And that he was buried, and 
       that he rose again the third 
       day according to the 
       scriptures: 
```

```bash
kjv 1 cor 15:1-4 -b -d -w 40
```

```
1 Corinthians 15:1 Moreover, brethren, I 
declare unto you the gospel which I 
preached unto you, which also ye have 
received, and wherein ye stand; 

1 Corinthians 15:2 By which also ye are 
saved, if ye keep in memory what I 
preached unto you, unless ye have 
believed in vain. 

1 Corinthians 15:3 For I delivered unto 
you first of all that which I also 
received, how that Christ died for our 
sins according to the scriptures; 

1 Corinthians 15:4 And that he was 
buried, and that he rose again the 
third day according to the scriptures: 
```

**Comment by bontibon** [comment]
I think I have most of those features now. Anything missing can likely be done using a shell script wrapper.
