### ISSUE TITLE
Missing header file "readline"

### ISSUE THREAD

**Issue by cowboy8625** [bontibon/kjv#16]
```c
src/kjv.c:14:10: fatal error: readline/readline.h: No such file or directory
   14 | #include <readline/readline.h>
      |          ^~~~~~~~~~~~~~~~~~~~~
```

getting the above error  and for the life of me I can not fine this header.   I am on a Debian base distro.

**Comment by bontibon** [comment]
You need to install the readline development libraries:

sudo apt-get install libreadline-dev

**Comment by cowboy8625** [comment]
Yes sir that fixed it!  Thank you!  I am closing this issue!
