### ISSUE TITLE
How did you make kjv.tsv

### ISSUE THREAD

**Issue by JonathanBuchh** [bontibon/kjv#19]
Thank you so much for making this script. It is so convenient, intuitive, and helpful.

I was just wondering how you made the `kjv.tsv` file. Did you make a script to scrape text from BibleGateway, manipulate a `.txt` file, or do something completely different? How would you recommend someone go about making a `.tsv` file for the Bible?

Thanks.

**Comment by ghost** [comment]
It was a while ago, but I just found a plaintext copy somewhere online and used it to generate the file.

Please make sure you watch this documentary about why the King James Version is the only English translation you should use: https://archive.org/details/new-world-order-bible-versions-full-movie.
