### ISSUE TITLE
Is this still manteined?

### ISSUE THREAD

**Issue by HayyaSylvy** [bontibon/kjv#24]
First and foremost, it is amazing to find that Linux is not fully overrun by atheists and  there is an actual amazing script to read the word of our lord from a command-line. However, it appears that this app haven't got a meaningful commit in almost 2 years.
If @layeh is still seeing this, can you transfer lead to someone that can maintain it up to date? It would be such a shame to see a useful script like this get abandonned.

**Comment by flamendless** [comment]
I don't see anything that can be improved anymore 🤔

**Comment by u873838** [comment]
> it appears that this app haven't got a meaningful commit in almost 2 years

The Word of God hasn't changed for nearly 2000 years, and yet doesn't require any updates.


If you find any bugs, please report them and a best effort will be made to fix them.
