### ISSUE TITLE
2 Esidras missing with Luke Smith's apocrypha kjv.tsv

### ISSUE THREAD

**Issue by catfromplan9** [bontibon/kjv#26]
This happens with any tsv that is 79 or more books. I added extra book to test, behavior is as follows:

78 and lower: untested
79-80 books: 1 book is not available, `kjv -l` reports a book with the name of " ()" for that book.
81+ books: Same behavior as before, except that any additional books will not display in `kjv -l` as anything, not even " ()".

By adding the book "Test" to the tsv at line 1, 2 Esidras becomes visible and "Test" becomes the book " ()" which is inaccessible. This is fine as a temporary solution but still makes the `kjv -l` have that " ()" entry. There is only ever 1 book labeled " ()" and so with 81+ books when more than 1 book will disappear, I cannot just add a book "Test" to my tsv to work around the bug to be the " ()". This is a problem for Ethiopian orthodox because theres going to be quite a few hidden books.

**Comment by u873838** [comment]
There are only 66 books in the Bible. The Apocrypha is simply that: apocryphal.

Please [watch this video](https://www.youtube.com/watch?v=4UCw4Fr-KxM) to see what the Bible says you must do to be saved from Hell.

**Comment by catfromplan9** [comment]
> There are only 66 books in the Bible. The Apocrypha is simply that: apocryphal.
> 
> Please [watch this video](https://www.youtube.com/watch?v=4UCw4Fr-KxM) to see what the Bible says you must do to be saved from Hell.

Yeah well that aside you still have a bug in the software. I want to be able to read the apocrypha, and this program breaks when I've added it.
