### ISSUE TITLE
2 Esidras missing with Luke Smith's apocrypha kjv.tsv

### ISSUE THREAD

**Issue by catfromplan9** [bontibon/kjv#27]
Preface: I opened this issue before, it got closed, so I'm reopening it. What you think the number of books in the bible should be has no significance here. The facts are that your software has a bug. I am willing to look into this and give a PR if you dont want to, but please do not close my issue. That is highly disrespectful. Do not try to convert me into protestantism. Allow orthodox christians to have complete bibles if they provide their own tsv without encountering bugs. Just keep this issue opened and do not respond if you don't wish to help.

This happens with any tsv that is 79 or more books. I added extra book to test, behavior is as follows:

78 and lower: untested
79-80 books: 1 book is not available, kjv -l reports a book with the name of " ()" for that book.
81+ books: Same behavior as before, except that any additional books will not display in kjv -l as anything, not even " ()".

By adding the book "Test" to the tsv at line 1, 2 Esidras becomes visible and "Test" becomes the book " ()" which is inaccessible. This is fine as a temporary solution but still makes the kjv -l have that " ()" entry. There is only ever 1 book labeled " ()" and so with 81+ books when more than 1 book will disappear, I cannot just add a book "Test" to my tsv to work around the bug to be the " ()". This is a problem for Ethiopian orthodox because theres going to be quite a few hidden books.

**Comment by catfromplan9** [comment]
Problem with supplied TSV file, closing this

**Comment by raphaeltannous** [comment]
> Preface: I opened this issue before, it got closed, so I'm reopening it. What you think the number of books in the bible should be has no significance here. The facts are that your software has a bug. I am willing to look into this and give a PR if you dont want to, but please do not close my issue. That is highly disrespectful. Do not try to convert me into protestantism. Allow orthodox christians to have complete bibles if they provide their own tsv without encountering bugs. Just keep this issue opened and do not respond if you don't wish to help.
> 
> This happens with any tsv that is 79 or more books. I added extra book to test, behavior is as follows:
> 
> 78 and lower: untested 79-80 books: 1 book is not available, kjv -l reports a book with the name of " ()" for that book. 81+ books: Same behavior as before, except that any additional books will not display in kjv -l as anything, not even " ()".
> 
> By adding the book "Test" to the tsv at line 1, 2 Esidras becomes visible and "Test" becomes the book " ()" which is inaccessible. This is fine as a temporary solution but still makes the kjv -l have that " ()" entry. There is only ever 1 book labeled " ()" and so with 81+ books when more than 1 book will disappear, I cannot just add a book "Test" to my tsv to work around the bug to be the " ()". This is a problem for Ethiopian orthodox because theres going to be quite a few hidden books.

Hey,

The project seems to be unmaintained, https://github.com/layeh/kjv/pull/23.
I would like to point to my fork at https://github.com/rofe33/kjv-layeh/tree/kjv-new-options.

I also  created a bunch of repositories for different versions, like:
- https://github.com/rofe33/RKJNT
- https://github.com/rofe33/BBE
- https://github.com/rofe33/DARBY
- and so on...

> However, I am not that familiar with the C Programing Language.

**Comment by catfromplan9** [comment]
> > Preface: I opened this issue before, it got closed, so I'm reopening it. What you think the number of books in the bible should be has no significance here. The facts are that your software has a bug. I am willing to look into this and give a PR if you dont want to, but please do not close my issue. That is highly disrespectful. Do not try to convert me into protestantism. Allow orthodox christians to have complete bibles if they provide their own tsv without encountering bugs. Just keep this issue opened and do not respond if you don't wish to help.
> > This happens with any tsv that is 79 or more books. I added extra book to test, behavior is as follows:
> > 78 and lower: untested 79-80 books: 1 book is not available, kjv -l reports a book with the name of " ()" for that book. 81+ books: Same behavior as before, except that any additional books will not display in kjv -l as anything, not even " ()".
> > By adding the book "Test" to the tsv at line 1, 2 Esidras becomes visible and "Test" becomes the book " ()" which is inaccessible. This is fine as a temporary solution but still makes the kjv -l have that " ()" entry. There is only ever 1 book labeled " ()" and so with 81+ books when more than 1 book will disappear, I cannot just add a book "Test" to my tsv to work around the bug to be the " ()". This is a problem for Ethiopian orthodox because theres going to be quite a few hidden books.
> 
> Hey,
> 
> The project seems to be unmaintained, #23. I would like to point to my fork at https://github.com/rofe33/kjv-layeh/tree/kjv-new-options.
> 
> I also created a bunch of repositories for different versions, like:
> 
>     * https://github.com/rofe33/RKJNT
> 
>     * https://github.com/rofe33/BBE
> 
>     * https://github.com/rofe33/DARBY
> 
>     * and so on...
> 
> 
> > However, I am not that familiar with the C Programing Language.

Oh, thank you! I can package your versions for gentoo, if you'd like

**Comment by raphaeltannous** [comment]
> Oh, thank you! I can package your versions for Gentoo, if you'd like

No, thank you. It is not a big deal, I am planning to remove them and making an update on https://github.com/rofe33/Bibles (I won't remove the PDFs just the terminal stuff), and the terminal bibles. 

I don't want to do something that nobody will use, if someone wants a bible version, then I will add it. For now I am just maintaining with what I have for the PDF versions.

Thank you! If you want me to create a version for you let me know! I will be glad to add one for you.

I will be updating, my projects and see what is best to do. For now I am not that familiar with C, I am more a python guy.

**Comment by raphaeltannous** [comment]
Just to clarify, I want to delete the terminal stuff, because I am not familiar with C and I can't maintain the code. 
I am not sure how long it will stay working and compiling, and I just want more features added!

I may create another script that can do a lot of things using python, and similar to this project.

God Bless You!

**Comment by catfromplan9** [comment]
> > Oh, thank you! I can package your versions for Gentoo, if you'd like
> 
> No, thank you. It is not a big deal, I am planning to remove them and making an update on https://github.com/rofe33/Bibles (I won't remove the PDFs just the terminal stuff), and the terminal bibles.
> 
> I don't want to do something that nobody will use, if someone wants a bible version, then I will add it. For now I am just maintaining with what I have for the PDF versions.
> 
> Thank you! If you want me to create a version for you let me know! I will be glad to add one for you.
> 
> I will be updating, my projects and see what is best to do. For now I am not that familiar with C, I am more a python guy.

Would you be willing to make NIV bible tsv?

**Comment by raphaeltannous** [comment]
> > > Oh, thank you! I can package your versions for Gentoo, if you'd like
> > 
> > 
> > No, thank you. It is not a big deal, I am planning to remove them and making an update on https://github.com/rofe33/Bibles (I won't remove the PDFs just the terminal stuff), and the terminal bibles.
> > I don't want to do something that nobody will use, if someone wants a bible version, then I will add it. For now I am just maintaining with what I have for the PDF versions.
> > Thank you! If you want me to create a version for you let me know! I will be glad to add one for you.
> > I will be updating, my projects and see what is best to do. For now I am not that familiar with C, I am more a python guy.
> 
> Would you be willing to make NIV bible tsv?

Yes! But from where do I get the data of the NIV bible? For now I am getting the data from https://bible4u.net/en/download#en
