### ISSUE TITLE
up arrow to get command history with `kjv>` prompt

### ISSUE THREAD

**Issue by wickedjargon** [bontibon/kjv#6]
It would be nice if the up arrow would pull the command history for when the user is prompted with `kjv>`

**Comment by ipstone** [comment]
I am guessing with the current design the kjv (focusing on the content), it may be easier to do `history | grep kjv` instead of adding a history command tracking file to kjv.

**Comment by bontibon** [comment]
Added with ebd36819a5044bfd7c08f535e9ae85a1e318f5b2.
